databases:
  - name: psocial_api
    databaseName: psocial_api
    user: psocial_api

services:
  - type: web
    name: psocial_api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn psocial_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: psocial_api
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4